apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  postgres-username: cG9zdGdyZXM=
  postgres-password: YWRtaW5wYXNzd29yZA==
  access_token: ZGFjMThhYTIwMmUxNTJmMTIwMTk0Yzc4NDg1ZTk4YjJhNmY1NzY4MzlhZjA5NTg5NWY3MzZlM2Q3MDhhNDVhYWMzYWQwYTc5MmM5MWI2MzJkZjEzMTAwZTA5NTNmZmE3MzNhYTFmNTYyYjY2ZWNlNTllYTAzMzlkY2MzZjMwMGY=
